### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [zqpmaster/ZhengFangJiaoWuXiTong#1]
课程请求无响应，请问现在你那里能正常得到课程的数据吗

**Comment by zqpmaster** [comment]
抓包看下，请求返回码是什么。

**Comment by ghost** [comment]
正确的url我改了一下，传过去的是正确的学号和名字
Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: found (302)" UserInfo=0x7fe05ad39540 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7fe05d1488c0> { URL: http://202.115.80.153/xskbcx.aspx?xh=3213123&xm=321321312&gnmkdm=N121603 } { status code: 302, headers {

```
"Cache-Control" = private;

"Content-Length" = 117;

"Content-Type" = "text/html; charset=gb2312";

Date = "Thu, 24 Mar 2016 01:48:10 GMT";

Location = "";

Server = "Microsoft-IIS/6.0";

"X-Aspnet-Version" = "1.1.4322";

"X-Powered-By" = "ASP.NET";
```

} }, NSErrorFailingURLKey=http://202.115.80.153/xskbcx.aspx?xh=123456&xm=213123&gnmkdm=N121603, com.alamofire.serialization.response.error.data=<3c68746d 6c3e3c68 6561643e 3c746974 6c653e4f 626a6563 74206d6f 7665643c 2f746974 6c653e3c 2f686561 643e3c62 6f64793e 0d0a3c68 323e4f62 6a656374 206d6f76 65642074 6f203c61 20687265 663d2727 3e686572 653c2f61 3e2e3c2f 68323e0d 0a3c2f62 6f64793e 3c2f6874 6d6c3e0d 0a>, NSLocalizedDescription=Request failed: found (302)}

**Comment by zqpmaster** [comment]
我记得课程请求的时候要带refer参数的。你在chrome里模拟请求看看浏览器的HTTP请求都带什么参数。

**Comment by zqpmaster** [comment]
你已经模拟登录了吗。要拿到cookie的。

**Comment by ghost** [comment]
登录成功的

**Comment by ghost** [comment]
参数：xh   xm gnmkdm

**Comment by zqpmaster** [comment]
不是这个，看下请求头header里的参数。

**Comment by ghost** [comment]
URL  status  Response Code    protocol  SSL Method   Kept Alive Content-Type  Client-Address  Remote Address   没有refer

**Comment by lingtingSir** [comment]
有找到办法解决吗，想加个QQ363905547，这样好联系一些~

**Comment by ghost** [comment]
我结合博客和源码在看了一遍，项目源码Cookies这一块是没有相关代码的，可以在上传一次比较完整的源码吗

**Comment by zqpmaster** [comment]
cookie就是我博客里写的那些了，没别的。还有这个项目是2014年上半年做的，现在正方教务系统或许也改版了。现在只能给你提供些思路，我当时是先在chrome里点网页看它的请求都是些什么，然后在跟自己客户端的请求对比，一步步搞出来的。
